kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: crossplane-poc
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8000
        protocol: TCP
      - containerPort: 443
        hostPort: 4430
        protocol: TCP
